load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_cxx_toolchain(
    name = "cxx",
    cxx_flags = ["-std=c++17", "-Wall", "-Werror"],
    visibility = ["PUBLIC"]
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)
