cxx_library(
    name = "list",
    exported_headers = [
        "list.h",
    ],
    visibility = [
        "PUBLIC",
    ]
)

cxx_test(
    name = "list_test",
    srcs = [
        "list_test.cc"
    ],
    deps = [
        ":list",
        "//third_party/googletest:gtest",
        "//third_party/googletest:gmock",
    ]
)
